version: '3.8'

networks:
  vpn:
    ipam:
      config:
        - subnet: 172.19.0.0/24

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=${SERVER_REGIONS}
    ports:
      # qBittorrent
      - 8081:8081
      - 6881:6881
      # Sonarr
      - 8989:8989
    networks:
      vpn:
        ipv4_address: 172.19.0.2
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent/config:/config
      - ./downloads:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: "service:gluetun"
    restart: unless-stopped
    healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: 60s
        retries: 3
        start_period: 20s
        timeout: 10s

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sonarr/config:/config
      - ./downloads:/downloads
      - ./tv:/tv
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: "service:gluetun"
    restart: unless-stopped 