services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ./nginx-proxy-mgr:/data
      - ./nginx-proxy-mgr/letsencrypt:/etc/letsencrypt
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped
    ports:
      - '9443:9443'
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./nextcloud:/config
      - /mnt/seagate-portable/nextcloud:/data
    ports:
      - '5443:443'
    restart: unless-stopped
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERBOSITY=-vv #optional
    volumes:
      - ./fail2ban:/config
      - /var/log:/var/log:ro
      - ./nextcloud/log:/remotelogs/nextcloud:ro #optional
      - ./nginx-proxy-mgr/log:/remotelogs/nginx:ro #optional
      - ./overseerr/log:/remotelogs/overseerr:ro #optional
      - ./prowlarr/log:/remotelogs/prowlarr:ro #optional
      - ./radarr/log:/remotelogs/radarr:ro #optional
      - ./sonarr/log:/remotelogs/sonarr:ro #optional
    restart: unless-stopped
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '4167:67/udp'
      - '4168:68/udp'
      - '4180:80/tcp'
      - '4130:3000'
    volumes:
      - ./adguard/config:/opt/adguardhome/conf
      - ./adguard/work:/opt/adguardhome/work
    restart: unless-stopped
