version: '3.8'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - 32400:32400
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./tv:/tv
      - ./movies:/movies
    restart: unless-stopped 

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./tautulli/config:/config
      - ./plex/config/Library/Application Support/Plex Media Server/Logs:/logs:ro
    ports:
      - 8181:8181
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./overseerr/config:/config
      - ./tv:/tv
      - ./movies:/movies
    ports:
      - 5055:5055
    restart: unless-stopped