version: '3.8'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    runtime: nvidia
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - 32400:32400
    networks:
      media_net:
        ipv4_address: 192.168.68.100
    volumes:
      - ./plex/config:/config
      - /mnt/elements-portable:/media1
      - /mnt/wdc-hdd/Movies:/media2
    security_opt:
      - apparmor=unconfined
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped 

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./tautulli/config:/config
    ports:
      - 8181:8181
    networks:
      - media_net
    security_opt:
      - apparmor=unconfined
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./overseerr/config:/config
    ports:
      - 5055:5055
    networks:
      - media_net
    security_opt:
      - apparmor=unconfined
    restart: unless-stopped

networks:
  media_net:
    ipam:
      config:
        - subnet: 192.168.68.0/24

